{
 "title": "数据监测系统历史数据",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align:center;color:#3d71d9;font-size:46px;font-family:'LXGW WenKai Mono'\">《基于嵌入式Linux与EMQX云平台的数据监测系统设计与实现》</h1>\r\n<h1 style=\"text-align:center;color:#3d71d9;font-size:46px;font-family:'LXGW WenKai Mono'\">传感器历史数据面板</h1>"
   },
   "targets": [
    { "topic": "led" }
   ]
  },
  {
   "title": "温湿度历史数据（DHT11 sensor）",
   "type": "timeseries",
   "description": "1. 红色温度预警线，当温度大于30℃时将触发预警\n2. 蓝色湿度预警线，当湿度大于70%H时将触发预警",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "dataset": "emqx",
     "rawSql": "select cast(json_unquote(json_extract(payload, '$.temp')) as decimal(10, 0))   AS \"temp\",\r\n       cast(json_unquote(json_extract(payload, '$.humi')) as decimal(10, 0))   AS \"humi\",\r\n       cast(json_unquote(json_extract(payload, '$.status')) as decimal(10, 0)) AS \"status\",\r\n       created_at                                                              AS \"time\"\r\nfrom emqx_messages\r\nwhere topic=\"dht11\"\r\norder by id desc\r\nlimit 10000;"
    }
   ]
  },
  {
   "title": "光照强度历史数据（photo sensor）",
   "type": "timeseries",
   "description": "蓝色光照度预警线，当光照值大于300lux时将触发预警",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "select cast(json_unquote(json_extract(payload, '$.raw')) as decimal(10, 0))   AS \"raw\",\r\n       cast(json_unquote(json_extract(payload, '$.light')) as decimal(10, 0))   AS \"light\",\r\n       cast(json_unquote(json_extract(payload, '$.voltage')) as decimal(10, 0))   AS \"voltage\",\r\n       cast(json_unquote(json_extract(payload, '$.status')) as decimal(10, 0))   AS \"status\",\r\n       unix_timestamp(created_at)                                              AS \"time_sec\"\r\nfrom emqx_messages\r\nwhere topic=\"light\"\r\norder by id desc\r\nlimit 10000;"
    }
   ]
  },
  {
   "title": "火焰传感器历史状态",
   "type": "timeseries",
   "description": "当原始值小于4000时，表明有明火将触发预警",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "# fire\r\nselect cast(json_unquote(json_extract(payload, '$.raw')) as decimal(10, 0))     AS \"raw\",\r\n       cast(json_unquote(json_extract(payload, '$.voltage')) as decimal(10, 0)) AS \"voltage\",\r\n       cast(json_unquote(json_extract(payload, '$.status')) as decimal(10, 0))  AS \"status\",\r\n       unix_timestamp(created_at)                                               AS \"time_sec\"\r\nfrom emqx_messages\r\nwhere topic = \"fire\"\r\norder by id desc\r\nlimit 10000;"
    }
   ]
  },
  {
   "title": "LED 灯历史状态",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select cast(json_unquote(json_extract(payload, '$.redled_status')) as decimal(10, 0))   AS \"redled_status\",\r\n       cast(json_unquote(json_extract(payload, '$.greenled_status')) as decimal(10, 0)) AS \"greenled_status\",\r\n       cast(json_unquote(json_extract(payload, '$.blueled_status')) as decimal(10, 0))  AS \"blueled_status\",\r\n       unix_timestamp(created_at)                                                       AS \"time_sec\"\r\nfrom emqx_messages\r\nwhere topic = \"led\"\r\norder by id desc\r\nlimit 10000;"
    }
   ]
  },
  {
   "title": "蜂鸣器历史状态",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select cast(json_unquote(json_extract(payload, '$.status')) as decimal(10, 0)) AS \"status\",\r\n       unix_timestamp(created_at)                                              AS \"time_sec\"\r\nfrom emqx_messages\r\nwhere topic = \"beep\"\r\norder by id desc\r\nlimit 10000;"
    }
   ]
  },
  {
   "title": "姿态历史数据（ICM20608 sensor）",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "accG" } },
   "targets": [
    {
     "rawSql": "select cast(json_unquote(json_extract(payload, '$.temp')) as decimal(10, 0))    AS \"temp\",\r\n       cast(json_unquote(json_extract(payload, '$.\"gyro.x\"')) as decimal(10, 0))  AS \"gyro.x\",\r\n       cast(json_unquote(json_extract(payload, '$.\"gyro.y\"')) as decimal(10, 0))  AS \"gyro.y\",\r\n       cast(json_unquote(json_extract(payload, '$.\"gyro.z\"')) as decimal(10, 0))  AS \"gyro.z\",\r\n       cast(json_unquote(json_extract(payload, '$.\"accel.x\"')) as decimal(10, 0)) AS \"accel.x\",\r\n       cast(json_unquote(json_extract(payload, '$.\"accel.y\"')) as decimal(10, 0)) AS \"accel.y\",\r\n       cast(json_unquote(json_extract(payload, '$.\"accel.z\"')) as decimal(10, 0)) AS \"accel.z\",\r\n       cast(json_unquote(json_extract(payload, '$.status')) as decimal(10, 0))  AS \"status\",\r\n       created_at                                                               AS \"time\"\r\nfrom emqx_messages\r\nwhere topic = \"icm20608\"\r\norder by id desc \r\nlimit 10000;"
    }
   ]
  },
  {
   "title": "环境光历史数据（ AP3216C sensor）",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "select cast(json_unquote(json_extract(payload, '$.ir')) as decimal(10, 0))     AS \"ir\",\r\n       cast(json_unquote(json_extract(payload, '$.ps')) as decimal(10, 0))     AS \"ps\",\r\n       cast(json_unquote(json_extract(payload, '$.als')) as decimal(10, 0))    AS \"als\",\r\n       cast(json_unquote(json_extract(payload, '$.status')) as decimal(10, 0)) AS \"status\",\r\n       created_at                                                              AS \"time\"\r\nfrom emqx_messages\r\nwhere topic = \"ap3216c\"\r\norder by id desc\r\nlimit 10000;\r\n"
    }
   ]
  }
 ]
}